pub mod buffer;
pub mod cursor;
pub mod document;
pub mod edit_ops;
pub mod editor;
pub mod history;
pub mod selection;
pub mod types;
pub mod view;
pub mod width_manager;

pub use buffer::Buffer;
pub use cursor::{cursor_manager::CursorManager, types::*};
pub use document::{Document, document_manager::DocumentManager, error_types::*, types::*};
pub use editor::Editor;
pub use history::{Edit, Transaction, UndoHistory, ViewState};
pub use selection::{selection_manager::SelectionManager, types::Selection};
pub use types::*;
pub use view::{View, ViewId, ViewManager};
use width_manager::WidthManager;
